const data = [
    {
      "eventDate": "1/25/2018",
      "clientName": "Equinix",
      "cityName": "Houston",
      "state": "TX",
      "eventTitle": "Interdependence Day – Internet of Things",
      "venueName": "Fleming's",
      "clientIndustry": "Data Center",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT & Business",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 35,
      "yes": 39,
      "panelists": 4,
      "yesProspects": 27,
      "yesSponsor": 8,
      "bdiRecruit": 27,
      "sponsorRecruit": 0,
      "confirmed": 20,
      "voicemail": 3,
      "unavailable": 4,
      "yesAdjusted": 49,
      "yesProspectsAdjusted": 41,
      "finalAttendees": 35,
      "finalProspects": 27,
      "finalSponsor": 8,
      "no": 49,
      "nsCancelTotal": 10,
      "noShows": 4,
      "cancelDayOf": 3,
      "cancelOneDay": 3,
      "cancelPanel": 0,
      "panelTiersSent": 3,
      "listSize": 3928,
      "contentRating": 1,
      "contentCategory": "IoT",
      "contentCategoryMutEx": "IoT",
      "seniorityLevel": "Manager",
      "responseRate": "2.29%",
      "rsvpRate": "1.04%",
      "onversionRate": "0.69%"
    },
    {
      "eventDate": "4/24/2018",
      "clientName": "Hitachi",
      "cityName": "Dallas",
      "state": "TX",
      "eventTitle": "EnterpriseOnEdge",
      "venueName": "Fearing's",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 22,
      "panelists": 2,
      "yesProspects": 12,
      "yesSponsor": 9,
      "bdiRecruit": 13,
      "sponsorRecruit": 9,
      "confirmed": 8,
      "voicemail": 2,
      "unavailable": 3,
      "yesAdjusted": 37,
      "yesProspectsAdjusted": 29,
      "finalAttendees": 21,
      "finalProspects": 13,
      "finalSponsor": 9,
      "no": 119,
      "nsCancelTotal": 15,
      "noShows": 9,
      "cancelDayOf": 4,
      "cancelOneDay": 1,
      "cancelPanel": 1,
      "panelTiersSent": 9,
      "listSize": 2661,
      "contentRating": 3,
      "contentCategory": "Cloud",
      "contentCategoryMutEx": "Cloud",
      "seniorityLevel": "Director",
      "responseRate": "5.56%",
      "rsvpRate": "1.09%",
      "onversionRate": "0.49%"
    },
    {
      "eventDate": "4/26/2018",
      "clientName": "Hitachi",
      "cityName": "New York",
      "state": "NY",
      "eventTitle": "EnterpriseOnEdge",
      "venueName": "Gabriel Kreuther",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 28,
      "panelists": 3,
      "yesProspects": 13,
      "yesSponsor": 12,
      "bdiRecruit": 16,
      "sponsorRecruit": 0,
      "confirmed": 0,
      "voicemail": 0,
      "unavailable": 0,
      "yesAdjusted": 45,
      "yesProspectsAdjusted": 33,
      "finalAttendees": 19,
      "finalProspects": 10,
      "finalSponsor": 9,
      "no": 84,
      "nsCancelTotal": 17,
      "noShows": 6,
      "cancelDayOf": 0,
      "cancelOneDay": 11,
      "cancelPanel": 0,
      "panelTiersSent": 4,
      "listSize": 5706,
      "contentRating": 3,
      "contentCategory": "Cloud",
      "contentCategoryMutEx": "Cloud",
      "seniorityLevel": "Director",
      "responseRate": "2.05%",
      "rsvpRate": "0.58%",
      "onversionRate": "0.18%"
    },
    {
      "eventDate": "5/30/2018",
      "clientName": "Silver Peak",
      "cityName": "Houston",
      "state": "TX",
      "eventTitle": "The Rise of SD-WAN - Roundtable Lunch for IT and Business Leaders",
      "venueName": "Fleming's",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 29,
      "panelists": 3,
      "yesProspects": 22,
      "yesSponsor": 5,
      "bdiRecruit": 24,
      "sponsorRecruit": 0,
      "confirmed": 12,
      "voicemail": 9,
      "unavailable": 3,
      "yesAdjusted": 53,
      "yesProspectsAdjusted": 49,
      "finalAttendees": 19,
      "finalProspects": 14,
      "finalSponsor": 5,
      "no": 88,
      "nsCancelTotal": 24,
      "noShows": 10,
      "cancelDayOf": 5,
      "cancelOneDay": 8,
      "cancelPanel": 1,
      "panelTiersSent": 1,
      "listSize": 2769,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "4.95%",
      "rsvpRate": "1.77%",
      "onversionRate": "0.51%"
    },
    {
      "eventDate": "6/19/2018",
      "clientName": "Silver Peak",
      "cityName": "Indianapolis",
      "state": "IN",
      "eventTitle": "The Rise of SD-WAN - Roundtable Lunch for IT and Business Leaders",
      "venueName": "Fleming's",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 24,
      "panelists": 5,
      "yesProspects": 17,
      "yesSponsor": 4,
      "bdiRecruit": 17,
      "sponsorRecruit": 0,
      "confirmed": 10,
      "voicemail": 4,
      "unavailable": 5,
      "yesAdjusted": 40,
      "yesProspectsAdjusted": 38,
      "finalAttendees": 18,
      "finalProspects": 4,
      "finalSponsor": 4,
      "no": 175,
      "nsCancelTotal": 16,
      "noShows": 7,
      "cancelDayOf": 7,
      "cancelOneDay": 0,
      "cancelPanel": 2,
      "panelTiersSent": 4,
      "listSize": 3557,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "5.99%",
      "rsvpRate": "1.07%",
      "onversionRate": "0.11%"
    },
    {
      "eventDate": "7/19/2018",
      "clientName": "MuleSoft",
      "cityName": "New York",
      "state": "NY",
      "eventTitle": "The CIO Roundtable",
      "venueName": "NYSE Room",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 27,
      "panelists": 4,
      "yesProspects": 14,
      "yesSponsor": 11,
      "bdiRecruit": 17,
      "sponsorRecruit": 0,
      "confirmed": 12,
      "voicemail": 4,
      "unavailable": 1,
      "yesAdjusted": 42,
      "yesProspectsAdjusted": 33,
      "finalAttendees": 18,
      "finalProspects": 13,
      "finalSponsor": 5,
      "no": 72,
      "nsCancelTotal": 15,
      "noShows": 4,
      "cancelDayOf": 5,
      "cancelOneDay": 5,
      "cancelPanel": 1,
      "panelTiersSent": 4,
      "listSize": 1334,
      "contentRating": 2,
      "contentCategory": "IoT & AI",
      "contentCategoryMutEx": "AI",
      "seniorityLevel": "CXO",
      "responseRate": "7.87%",
      "rsvpRate": "2.47%",
      "onversionRate": "0.97%"
    },
    {
      "eventDate": "7/24/2018",
      "clientName": "SailPoint",
      "cityName": "New York",
      "state": "NY",
      "eventTitle": "The Enterprise CISO Roundtable - Identity is Security",
      "venueName": "NYSE - Hamilton Room",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Security Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 25,
      "yes": 50,
      "panelists": 4,
      "yesProspects": 37,
      "yesSponsor": 10,
      "bdiRecruit": 40,
      "sponsorRecruit": 0,
      "confirmed": 20,
      "voicemail": 5,
      "unavailable": 13,
      "yesAdjusted": 63,
      "yesProspectsAdjusted": 54,
      "finalAttendees": 45,
      "finalProspects": 35,
      "finalSponsor": 10,
      "no": 62,
      "nsCancelTotal": 13,
      "noShows": 5,
      "cancelDayOf": 4,
      "cancelOneDay": 3,
      "cancelPanel": 1,
      "panelTiersSent": 3,
      "listSize": 1320,
      "contentRating": 2,
      "contentCategory": "Enterprise Security",
      "contentCategoryMutEx": "Security",
      "seniorityLevel": "Director",
      "responseRate": "8.79%",
      "rsvpRate": "4.09%",
      "onversionRate": "2.65%"
    },
    {
      "eventDate": "10/4/2018",
      "clientName": "Quick Base",
      "cityName": "Dallas",
      "state": "TX",
      "eventTitle": "Turning Shadow IT into Shadow Innovation",
      "venueName": "Nick & Sam’s Restaurant",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 31,
      "panelists": 4,
      "yesProspects": 22,
      "yesSponsor": 5,
      "bdiRecruit": 26,
      "sponsorRecruit": 0,
      "confirmed": 17,
      "voicemail": 5,
      "unavailable": 4,
      "yesAdjusted": 47,
      "yesProspectsAdjusted": 42,
      "finalAttendees": 26,
      "finalProspects": 21,
      "finalSponsor": 5,
      "no": 85,
      "nsCancelTotal": 16,
      "noShows": 7,
      "cancelDayOf": 3,
      "cancelOneDay": 6,
      "cancelPanel": 0,
      "panelTiersSent": 3,
      "listSize": 2467,
      "contentRating": 2,
      "contentCategory": "Shaddow IT",
      "contentCategoryMutEx": "Shaddow IT",
      "seniorityLevel": "Manager",
      "responseRate": "5.15%",
      "rsvpRate": "1.70%",
      "onversionRate": "0.85%"
    },
    {
      "eventDate": "10/10/2018",
      "clientName": "Silver Peak",
      "cityName": "Atlanta",
      "state": "GA",
      "eventTitle": "The Rise of SD-WAN",
      "venueName": "Atlanta Fish Market",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 22,
      "panelists": 2,
      "yesProspects": 14,
      "yesSponsor": 6,
      "bdiRecruit": 13,
      "sponsorRecruit": 3,
      "confirmed": 10,
      "voicemail": 4,
      "unavailable": 2,
      "yesAdjusted": 37,
      "yesProspectsAdjusted": 31,
      "finalAttendees": 14,
      "finalProspects": 9,
      "finalSponsor": 5,
      "no": 80,
      "nsCancelTotal": 15,
      "noShows": 7,
      "cancelDayOf": 3,
      "cancelOneDay": 5,
      "cancelPanel": 0,
      "panelTiersSent": 7,
      "listSize": 2003,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "5.54%",
      "rsvpRate": "1.55%",
      "onversionRate": "0.45%"
    },
    {
      "eventDate": "10/18/2018",
      "clientName": "Silver Peak",
      "cityName": "St. Louis",
      "state": "MO",
      "eventTitle": "The Rise of SD-WAN",
      "venueName": "Fleming’s Prime Steakhouse",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 44,
      "panelists": 3,
      "yesProspects": 36,
      "yesSponsor": 5,
      "bdiRecruit": 39,
      "sponsorRecruit": 0,
      "confirmed": 21,
      "voicemail": 9,
      "unavailable": 9,
      "yesAdjusted": 65,
      "yesProspectsAdjusted": 60,
      "finalAttendees": 34,
      "finalProspects": 29,
      "finalSponsor": 5,
      "no": 50,
      "nsCancelTotal": 21,
      "noShows": 10,
      "cancelDayOf": 2,
      "cancelOneDay": 9,
      "cancelPanel": 0,
      "panelTiersSent": 2,
      "listSize": 3545,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "3.10%",
      "rsvpRate": "1.69%",
      "onversionRate": "0.82%"
    },
    {
      "eventDate": "10/23/2018",
      "clientName": "Xerox",
      "cityName": "New York",
      "state": "NY",
      "eventTitle": "Blockchain: The Future of Electronic Content Management",
      "venueName": "Xerox Exec Briefing Center Midtown",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT & Legal",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 37,
      "panelists": 5,
      "yesProspects": 28,
      "yesSponsor": 6,
      "bdiRecruit": 26,
      "sponsorRecruit": 2,
      "confirmed": 17,
      "voicemail": 7,
      "unavailable": 7,
      "yesAdjusted": 54,
      "yesProspectsAdjusted": 50,
      "finalAttendees": 27,
      "finalProspects": 21,
      "finalSponsor": 6,
      "no": 71,
      "nsCancelTotal": 17,
      "noShows": 10,
      "cancelDayOf": 2,
      "cancelOneDay": 3,
      "cancelPanel": 2,
      "panelTiersSent": 3,
      "listSize": 6254,
      "contentRating": 1,
      "contentCategory": "Blockchain",
      "contentCategoryMutEx": "Blockchain",
      "seniorityLevel": "Director",
      "responseRate": "1.93%",
      "rsvpRate": "0.80%",
      "onversionRate": "0.34%"
    },
    {
      "eventDate": "10/25/2018",
      "clientName": "Cloudbakers",
      "cityName": "Denver",
      "state": "CO",
      "eventTitle": "Modernization with the Cloud",
      "venueName": "Elway's Downtown The Ritz Carlton",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Cloud Solutions",
      "attendeeFunction": "IT & Business",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 40,
      "panelists": 4,
      "yesProspects": 31,
      "yesSponsor": 6,
      "bdiRecruit": 33,
      "sponsorRecruit": 0,
      "confirmed": 22,
      "voicemail": 10,
      "unavailable": 1,
      "yesAdjusted": 51,
      "yesProspectsAdjusted": 46,
      "finalAttendees": 36,
      "finalProspects": 29,
      "finalSponsor": 7,
      "no": 117,
      "nsCancelTotal": 11,
      "noShows": 4,
      "cancelDayOf": 3,
      "cancelOneDay": 3,
      "cancelPanel": 1,
      "panelTiersSent": 6,
      "listSize": 5816,
      "contentRating": 3,
      "contentCategory": "Cloud Tansformation",
      "contentCategoryMutEx": "Cloud",
      "seniorityLevel": "Manager",
      "responseRate": "2.80%",
      "rsvpRate": "0.79%",
      "onversionRate": "0.50%"
    },
    {
      "eventDate": "10/30/2018",
      "clientName": "Cloudbakers",
      "cityName": "Cambridge",
      "state": "MA",
      "eventTitle": "Modernization with the Cloud",
      "venueName": "Catalyst",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Cloud Solutions",
      "attendeeFunction": "IT & Business",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 26,
      "panelists": 5,
      "yesProspects": 16,
      "yesSponsor": 6,
      "bdiRecruit": 20,
      "sponsorRecruit": 0,
      "confirmed": 11,
      "voicemail": 5,
      "unavailable": 4,
      "yesAdjusted": 42,
      "yesProspectsAdjusted": 37,
      "finalAttendees": 25,
      "finalProspects": 19,
      "finalSponsor": 5,
      "no": 134,
      "nsCancelTotal": 16,
      "noShows": 5,
      "cancelDayOf": 3,
      "cancelOneDay": 7,
      "cancelPanel": 1,
      "panelTiersSent": 4,
      "listSize": 9713,
      "contentRating": 3,
      "contentCategory": "Cloud Tansformation",
      "contentCategoryMutEx": "Cloud",
      "seniorityLevel": "Manager",
      "responseRate": "1.76%",
      "rsvpRate": "0.38%",
      "onversionRate": "0.20%"
    },
    {
      "eventDate": "2/28/2019",
      "clientName": "Silver Peak",
      "cityName": "Boston",
      "state": "MA",
      "eventTitle": "The Rise of the Business-First SD-WAN",
      "venueName": "Top of the Hub",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 23,
      "panelists": 4,
      "yesProspects": 14,
      "yesSponsor": 6,
      "bdiRecruit": 16,
      "sponsorRecruit": 1,
      "confirmed": 7,
      "voicemail": 7,
      "unavailable": 3,
      "yesAdjusted": 37,
      "yesProspectsAdjusted": 32,
      "finalAttendees": 20,
      "finalProspects": 14,
      "finalSponsor": 6,
      "no": 121,
      "nsCancelTotal": 14,
      "noShows": 3,
      "cancelDayOf": 0,
      "cancelOneDay": 9,
      "cancelPanel": 1,
      "panelTiersSent": 3,
      "listSize": 3730,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "4.10%",
      "rsvpRate": "0.86%",
      "onversionRate": "0.38%"
    },
    {
      "eventDate": "3/19/2019",
      "clientName": "MuleSoft",
      "cityName": "Chicago",
      "state": "IL",
      "eventTitle": "Digital Transformation Leadership Forum",
      "venueName": "The Gage",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 40,
      "yes": 35,
      "panelists": 4,
      "yesProspects": 23,
      "yesSponsor": 8,
      "bdiRecruit": 27,
      "sponsorRecruit": 0,
      "confirmed": 14,
      "voicemail": 11,
      "unavailable": 2,
      "yesAdjusted": 73,
      "yesProspectsAdjusted": 65,
      "finalAttendees": 19,
      "finalProspects": 13,
      "finalSponsor": 6,
      "no": 34,
      "nsCancelTotal": 38,
      "noShows": 12,
      "cancelDayOf": 10,
      "cancelOneDay": 8,
      "cancelPanel": 1,
      "panelTiersSent": 2,
      "listSize": 3707,
      "contentRating": 1,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Director",
      "responseRate": "2.67%",
      "rsvpRate": "1.75%",
      "onversionRate": "0.35%"
    },
    {
      "eventDate": "4/3/2019",
      "clientName": "Silver Peak",
      "cityName": "Denver",
      "state": "CO",
      "eventTitle": "The Rise of the Business-First SD-WAN",
      "venueName": "Guard and Grace",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 21,
      "panelists": 3,
      "yesProspects": 13,
      "yesSponsor": 5,
      "bdiRecruit": 16,
      "sponsorRecruit": 0,
      "confirmed": 10,
      "voicemail": 4,
      "unavailable": 2,
      "yesAdjusted": 30,
      "yesProspectsAdjusted": 25,
      "finalAttendees": 21,
      "finalProspects": 16,
      "finalSponsor": 5,
      "no": 123,
      "nsCancelTotal": 9,
      "noShows": 2,
      "cancelDayOf": 3,
      "cancelOneDay": 4,
      "cancelPanel": 0,
      "panelTiersSent": 3,
      "listSize": 5335,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "2.77%",
      "rsvpRate": "0.47%",
      "onversionRate": "0.30%"
    },
    {
      "eventDate": "4/4/2019",
      "clientName": "AppNeta",
      "cityName": "Toronto",
      "state": "ON",
      "eventTitle": "Transforming the Enterprise with Cloud Visibility",
      "venueName": "Leña Restaurante",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 35,
      "panelists": 3,
      "yesProspects": 28,
      "yesSponsor": 4,
      "bdiRecruit": 31,
      "sponsorRecruit": 0,
      "confirmed": 22,
      "voicemail": 3,
      "unavailable": 5,
      "yesAdjusted": 53,
      "yesProspectsAdjusted": 49,
      "finalAttendees": 31,
      "finalProspects": 24,
      "finalSponsor": 4,
      "no": 170,
      "nsCancelTotal": 18,
      "noShows": 4,
      "cancelDayOf": 2,
      "cancelOneDay": 10,
      "cancelPanel": 0,
      "panelTiersSent": 5,
      "listSize": 1329,
      "contentRating": 3,
      "contentCategory": "Cloud Visibility",
      "contentCategoryMutEx": "Cloud",
      "seniorityLevel": "Manager",
      "responseRate": "16.48%",
      "rsvpRate": "3.69%",
      "onversionRate": "1.81%"
    },
    {
      "eventDate": "4/4/2019",
      "clientName": "Silver Peak",
      "cityName": "Dallas",
      "state": "TX",
      "eventTitle": "The Rise of the Business-First SD-WAN",
      "venueName": "Fearing's @ the Ritz Carlton",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 19,
      "panelists": 2,
      "yesProspects": 14,
      "yesSponsor": 3,
      "bdiRecruit": 16,
      "sponsorRecruit": 0,
      "confirmed": 8,
      "voicemail": 6,
      "unavailable": 2,
      "yesAdjusted": 31,
      "yesProspectsAdjusted": 28,
      "finalAttendees": 19,
      "finalProspects": 16,
      "finalSponsor": 3,
      "no": 128,
      "nsCancelTotal": 12,
      "noShows": 5,
      "cancelDayOf": 4,
      "cancelOneDay": 1,
      "cancelPanel": 0,
      "panelTiersSent": 4,
      "listSize": 2113,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "7.38%",
      "rsvpRate": "1.33%",
      "onversionRate": "0.76%"
    },
    {
      "eventDate": "4/16/2019",
      "clientName": "Pivot3",
      "cityName": "Denver",
      "state": "CO",
      "eventTitle": "Winning the Digital Transformation IT Challenge",
      "venueName": "Guard and Grace",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "",
      "attendeeFunction": "Information Technology & Facilities",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 28,
      "panelists": 4,
      "yesProspects": 18,
      "yesSponsor": 6,
      "bdiRecruit": 22,
      "sponsorRecruit": 0,
      "confirmed": 11,
      "voicemail": 7,
      "unavailable": 4,
      "yesAdjusted": 42,
      "yesProspectsAdjusted": 36,
      "finalAttendees": 23,
      "finalProspects": 14,
      "finalSponsor": 6,
      "no": 88,
      "nsCancelTotal": 14,
      "noShows": 5,
      "cancelDayOf": 5,
      "cancelOneDay": 2,
      "cancelPanel": 1,
      "panelTiersSent": 5,
      "listSize": 3224,
      "contentRating": 2,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Manager",
      "responseRate": "3.85%",
      "rsvpRate": "1.12%",
      "onversionRate": "0.43%"
    },
    {
      "eventDate": "4/18/2019",
      "clientName": "Pivot3",
      "cityName": "Chicago",
      "state": "IL",
      "eventTitle": "Winning the Digital Transformation IT Challenge",
      "venueName": "The Gage",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "",
      "attendeeFunction": "Information Technology & Facilities",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 35,
      "panelists": 4,
      "yesProspects": 26,
      "yesSponsor": 6,
      "bdiRecruit": 29,
      "sponsorRecruit": 0,
      "confirmed": 9,
      "voicemail": 12,
      "unavailable": 4,
      "yesAdjusted": 57,
      "yesProspectsAdjusted": 52,
      "finalAttendees": 27,
      "finalProspects": 21,
      "finalSponsor": 6,
      "no": 164,
      "nsCancelTotal": 22,
      "noShows": 9,
      "cancelDayOf": 5,
      "cancelOneDay": 4,
      "cancelPanel": 1,
      "panelTiersSent": 7,
      "listSize": 9698,
      "contentRating": 2,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Manager",
      "responseRate": "2.23%",
      "rsvpRate": "0.54%",
      "onversionRate": "0.22%"
    },
    {
      "eventDate": "5/14/2019",
      "clientName": "Pivot3",
      "cityName": "New York",
      "state": "NY",
      "eventTitle": "Winning the Digital Transformation IT Challenge",
      "venueName": "Aureole",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "",
      "attendeeFunction": "Information Technology & Facilities",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 46,
      "panelists": 4,
      "yesProspects": 38,
      "yesSponsor": 6,
      "bdiRecruit": 40,
      "sponsorRecruit": 0,
      "confirmed": 21,
      "voicemail": 14,
      "unavailable": 4,
      "yesAdjusted": 90,
      "yesProspectsAdjusted": 86,
      "finalAttendees": 31,
      "finalProspects": 25,
      "finalSponsor": 6,
      "no": 198,
      "nsCancelTotal": 44,
      "noShows": 14,
      "cancelDayOf": 6,
      "cancelOneDay": 14,
      "cancelPanel": 2,
      "panelTiersSent": 7,
      "listSize": 17531,
      "contentRating": 2,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Manager",
      "responseRate": "1.62%",
      "rsvpRate": "0.49%",
      "onversionRate": "0.14%"
    },
    {
      "eventDate": "5/15/2019",
      "clientName": "Silver Peak",
      "cityName": "Palo Alto",
      "state": "CA",
      "eventTitle": "The Rise of the Business-First SD-WAN",
      "venueName": "Fleming's",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 23,
      "panelists": 2,
      "yesProspects": 17,
      "yesSponsor": 4,
      "bdiRecruit": 18,
      "sponsorRecruit": 1,
      "confirmed": 11,
      "voicemail": 4,
      "unavailable": 4,
      "yesAdjusted": 37,
      "yesProspectsAdjusted": 33,
      "finalAttendees": 21,
      "finalProspects": 17,
      "finalSponsor": 4,
      "no": 124,
      "nsCancelTotal": 14,
      "noShows": 2,
      "cancelDayOf": 4,
      "cancelOneDay": 6,
      "cancelPanel": 0,
      "panelTiersSent": 5,
      "listSize": 1691,
      "contentRating": 3,
      "contentCategory": "SD-WAN",
      "contentCategoryMutEx": "SD-WAN",
      "seniorityLevel": "Manager",
      "responseRate": "9.28%",
      "rsvpRate": "1.95%",
      "onversionRate": "1.01%"
    },
    {
      "eventDate": "5/16/2019",
      "clientName": "Pivot3",
      "cityName": "Dallas",
      "state": "TX",
      "eventTitle": "Winning the Digital Transformation IT Challenge",
      "venueName": "Nick & Sam’s Restaurant",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "",
      "attendeeFunction": "Information Technology & Facilities",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 34,
      "panelists": 5,
      "yesProspects": 24,
      "yesSponsor": 5,
      "bdiRecruit": 29,
      "sponsorRecruit": 0,
      "confirmed": 19,
      "voicemail": 6,
      "unavailable": 4,
      "yesAdjusted": 49,
      "yesProspectsAdjusted": 44,
      "finalAttendees": 31,
      "finalProspects": 26,
      "finalSponsor": 5,
      "no": 84,
      "nsCancelTotal": 15,
      "noShows": 3,
      "cancelDayOf": 2,
      "cancelOneDay": 7,
      "cancelPanel": 0,
      "panelTiersSent": 7,
      "listSize": 6948,
      "contentRating": 2,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Manager",
      "responseRate": "1.84%",
      "rsvpRate": "0.63%",
      "onversionRate": "0.37%"
    },
    {
      "eventDate": "6/19/2019",
      "clientName": "SpringML",
      "cityName": "Atlanta",
      "state": "GA",
      "eventTitle": "Getting Real with AI",
      "venueName": "Atlanta Fish Market",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT/Business/Media/Entertainment",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 44,
      "panelists": 3,
      "yesProspects": 25,
      "yesSponsor": 16,
      "bdiRecruit": 28,
      "sponsorRecruit": 0,
      "confirmed": 17,
      "voicemail": 3,
      "unavailable": 8,
      "yesAdjusted": 78,
      "yesProspectsAdjusted": 62,
      "finalAttendees": 34,
      "finalProspects": 18,
      "finalSponsor": 16,
      "no": 80,
      "nsCancelTotal": 34,
      "noShows": 10,
      "cancelDayOf": 2,
      "cancelOneDay": 16,
      "cancelPanel": 3,
      "panelTiersSent": 6,
      "listSize": 2900,
      "contentRating": 1,
      "contentCategory": "AI",
      "contentCategoryMutEx": "AI",
      "seniorityLevel": "Director",
      "responseRate": "4.90%",
      "rsvpRate": "2.14%",
      "onversionRate": "0.62%"
    },
    {
      "eventDate": "6/20/2019",
      "clientName": "Monotype",
      "cityName": "Chicago",
      "state": "IL",
      "eventTitle": "Brand Talks: A Roundtable Lunch on Brand Identity",
      "venueName": "The Gage",
      "clientIndustry": "",
      "clientIndustryMutEx": "",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 25,
      "yes": 51,
      "panelists": 4,
      "yesProspects": 39,
      "yesSponsor": 8,
      "bdiRecruit": 43,
      "sponsorRecruit": 0,
      "confirmed": 24,
      "voicemail": 12,
      "unavailable": 7,
      "yesAdjusted": 84,
      "yesProspectsAdjusted": 76,
      "finalAttendees": 42,
      "finalProspects": 34,
      "finalSponsor": 8,
      "no": 61,
      "nsCancelTotal": 33,
      "noShows": 10,
      "cancelDayOf": 1,
      "cancelOneDay": 0,
      "cancelPanel": 0,
      "panelTiersSent": 2,
      "listSize": 5866,
      "contentRating": "",
      "contentCategory": "",
      "contentCategoryMutEx": "",
      "seniorityLevel": "",
      "responseRate": "2.34%",
      "rsvpRate": "1.30%",
      "onversionRate": "0.58%"
    },
    {
      "eventDate": "6/25/2019",
      "clientName": "SpringML",
      "cityName": "Chicago",
      "state": "IL",
      "eventTitle": "Getting Real with AI",
      "venueName": "The Gage",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT/Business/Media/Entertainment",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 60,
      "panelists": 3,
      "yesProspects": 48,
      "yesSponsor": 9,
      "bdiRecruit": 51,
      "sponsorRecruit": 0,
      "confirmed": 29,
      "voicemail": 10,
      "unavailable": 12,
      "yesAdjusted": 99,
      "yesProspectsAdjusted": 90,
      "finalAttendees": 44,
      "finalProspects": 35,
      "finalSponsor": 9,
      "no": 161,
      "nsCancelTotal": 39,
      "noShows": 17,
      "cancelDayOf": 2,
      "cancelOneDay": 14,
      "cancelPanel": 1,
      "panelTiersSent": 6,
      "listSize": 11079,
      "contentRating": 1,
      "contentCategory": "AI",
      "contentCategoryMutEx": "AI",
      "seniorityLevel": "Director",
      "responseRate": "2.27%",
      "rsvpRate": "0.81%",
      "onversionRate": "0.32%"
    },
    {
      "eventDate": "6/26/2019",
      "clientName": "Silver Peak",
      "cityName": "Minneapolis",
      "state": "MN",
      "eventTitle": "Winning the Digital Transformation Networking Challenge",
      "venueName": "Ruth's Chris Steak House",
      "clientIndustry": "Computer Software",
      "clientIndustryMutEx": "Network Solutions",
      "attendeeFunction": "IT/Business",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 25,
      "panelists": 3,
      "yesProspects": 18,
      "yesSponsor": 4,
      "bdiRecruit": 21,
      "sponsorRecruit": 0,
      "confirmed": 13,
      "voicemail": 7,
      "unavailable": 1,
      "yesAdjusted": 36,
      "yesProspectsAdjusted": 32,
      "finalAttendees": 21,
      "finalProspects": 17,
      "finalSponsor": 4,
      "no": 99,
      "nsCancelTotal": 11,
      "noShows": 5,
      "cancelDayOf": 1,
      "cancelOneDay": 5,
      "cancelPanel": 1,
      "panelTiersSent": 3,
      "listSize": 6697,
      "contentRating": 2,
      "contentCategory": "Digital Transformation",
      "contentCategoryMutEx": "Digital Transformation",
      "seniorityLevel": "Manager",
      "responseRate": "1.96%",
      "rsvpRate": "0.48%",
      "onversionRate": "0.25%"
    },
    {
      "eventDate": "7/18/2019",
      "clientName": "PagerDuty",
      "cityName": "Cambridge",
      "state": "MA",
      "eventTitle": "Accelerating Digital Transformation with Real Time Operations",
      "venueName": "Catalyst",
      "clientIndustry": "",
      "clientIndustryMutEx": "",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 30,
      "panelists": 3,
      "yesProspects": 22,
      "yesSponsor": 8,
      "bdiRecruit": 22,
      "sponsorRecruit": 0,
      "confirmed": 10,
      "voicemail": 10,
      "unavailable": 2,
      "yesAdjusted": 44,
      "yesProspectsAdjusted": 39,
      "finalAttendees": 21,
      "finalProspects": 13,
      "finalSponsor": 8,
      "no": 146,
      "nsCancelTotal": 14,
      "noShows": 9,
      "cancelDayOf": 1,
      "cancelOneDay": 2,
      "cancelPanel": 1,
      "panelTiersSent": 4,
      "listSize": 5449,
      "contentRating": "",
      "contentCategory": "",
      "contentCategoryMutEx": "",
      "seniorityLevel": "",
      "responseRate": "3.40%",
      "rsvpRate": "0.72%",
      "onversionRate": "0.24%"
    },
    {
      "eventDate": "7/24/2019",
      "clientName": "PagerDuty",
      "cityName": "Dallas",
      "state": "TX",
      "eventTitle": "Accelerating Digital Transformation with Real Time Operations",
      "venueName": "Fearing's @ The Ritz-Carlton",
      "clientIndustry": "",
      "clientIndustryMutEx": "",
      "attendeeFunction": "IT",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 20,
      "yes": 32,
      "panelists": 4,
      "yesProspects": 22,
      "yesSponsor": 6,
      "bdiRecruit": 26,
      "sponsorRecruit": 0,
      "confirmed": 9,
      "voicemail": 7,
      "unavailable": 6,
      "yesAdjusted": 51,
      "yesProspectsAdjusted": 45,
      "finalAttendees": 19,
      "finalProspects": 14,
      "finalSponsor": 5,
      "no": 34,
      "nsCancelTotal": 19,
      "noShows": 11,
      "cancelDayOf": 2,
      "cancelOneDay": 3,
      "cancelPanel": 2,
      "panelTiersSent": 4,
      "listSize": 5514,
      "contentRating": "",
      "contentCategory": "",
      "contentCategoryMutEx": "",
      "seniorityLevel": "Manager",
      "responseRate": "1.43%",
      "rsvpRate": "0.82%",
      "onversionRate": "0.25%"
    },
    {
      "eventDate": "3/14/2019",
      "clientName": "SpringML",
      "cityName": "Columbus",
      "state": "OH",
      "eventTitle": "Getting Real with AI",
      "venueName": "Blackpoint",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT, FPR&A, Sales, Marketing",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 30,
      "yes": 35,
      "panelists": 5,
      "yesProspects": 26,
      "yesSponsor": 6,
      "bdiRecruit": 28,
      "sponsorRecruit": 0,
      "confirmed": 10,
      "voicemail": 4,
      "unavailable": 15,
      "yesAdjusted": 58,
      "yesProspectsAdjusted": 54,
      "finalAttendees": 26,
      "finalProspects": 20,
      "finalSponsor": 6,
      "no": 73,
      "nsCancelTotal": 23,
      "noShows": 8,
      "cancelDayOf": 6,
      "cancelOneDay": 4,
      "cancelPanel": 2,
      "panelTiersSent": 5,
      "listSize": 2023,
      "contentRating": 1,
      "contentCategory": "AI",
      "contentCategoryMutEx": "AI",
      "seniorityLevel": "Director",
      "responseRate": "6.28%",
      "rsvpRate": "2.67%",
      "onversionRate": "0.99%"
    },
    {
      "eventDate": "3/27/2019",
      "clientName": "Neudesic",
      "cityName": "Los Angeles",
      "state": "CA",
      "eventTitle": "Data-Driven Transformation",
      "venueName": "Fleming's Prime Steakhouse & Wine Bar",
      "clientIndustry": "Information Technology & Services",
      "clientIndustryMutEx": "Data Solutions",
      "attendeeFunction": "IT & Business",
      "attendeeFunctionMutEx": "IT",
      "targetAttendees": 25,
      "yes": 28,
      "panelists": 5,
      "yesProspects": 18,
      "yesSponsor": 7,
      "bdiRecruit": 21,
      "sponsorRecruit": 0,
      "confirmed": 10,
      "voicemail": 5,
      "unavailable": 6,
      "yesAdjusted": 39,
      "yesProspectsAdjusted": 34,
      "finalAttendees": 22,
      "finalProspects": 17,
      "finalSponsor": 5,
      "no": 126,
      "nsCancelTotal": 11,
      "noShows": 4,
      "cancelDayOf": 2,
      "cancelOneDay": 1,
      "cancelPanel": 2,
      "panelTiersSent": 5,
      "listSize": 2100,
      "contentRating": 2,
      "contentCategory": "Big Data & AI",
      "contentCategoryMutEx": "AI",
      "seniorityLevel": "Director",
      "responseRate": "7.62%",
      "rsvpRate": "1.62%",
      "onversionRate": "0.81%"
    },
    {
      "eventDate": "",
      "clientName": "",
      "cityName": "",
      "state": "",
      "eventTitle": "",
      "venueName": "",
      "clientIndustry": "",
      "clientIndustryMutEx": "",
      "attendeeFunction": "",
      "attendeeFunctionMutEx": "",
      "targetAttendees": 25,
      "yes": "",
      "panelists": 4,
      "yesProspects": "",
      "yesSponsor": "",
      "bdiRecruit": "",
      "sponsorRecruit": "",
      "confirmed": 14,
      "voicemail": "",
      "unavailable": "",
      "yesAdjusted": "",
      "yesProspectsAdjusted": 46,
      "finalAttendees": 26,
      "finalProspects": 19,
      "finalSponsor": 6,
      "no": 103,
      "nsCancelTotal": 19,
      "noShows": 7,
      "cancelDayOf": 3,
      "cancelOneDay": 6,
      "cancelPanel": 1,
      "panelTiersSent": 4,
      "listSize": 4774,
      "contentRating": "",
      "contentCategory": "",
      "contentCategoryMutEx": "",
      "seniorityLevel": "",
      "responseRate": "4.52%",
      "rsvpRate": "1.37%",
      "onversionRate": "0.60%"
    }
  ];

  console.log(data[0]);







$(function () {

    'use strict';
  
    (function () {
  
      var aside = $('.side-nav'),
  
          showAsideBtn = $('.show-side-btn'),
  
          contents = $('#contents');
  
      showAsideBtn.on("click", function () {
  
        $("#" + $(this).data('show')).toggleClass('show-side-nav');
  
        contents.toggleClass('margin');
  
      });
  
      if ($(window).width() <= 767) {
  
        aside.addClass('show-side-nav');
  
      }
      $(window).on('resize', function () {
  
        if ($(window).width() > 767) {
  
          aside.removeClass('show-side-nav');
  
        }
  
      });
  
      // dropdown menu in the side nav
      var slideNavDropdown = $('.side-nav-dropdown');
  
      $('.side-nav .categories li').on('click', function () {
  
        $(this).toggleClass('opend').siblings().removeClass('opend');
  
        if ($(this).hasClass('opend')) {
  
          $(this).find('.side-nav-dropdown').slideToggle('fast');
  
          $(this).siblings().find('.side-nav-dropdown').slideUp('fast');
  
        } else {
  
          $(this).find('.side-nav-dropdown').slideUp('fast');
  
        }
  
      });
  
      $('.side-nav .close-aside').on('click', function () {
  
        $('#' + $(this).data('close')).addClass('show-side-nav');
  
        contents.removeClass('margin');
  
      });
  
    }());
  
    // Start chart
  
    var chart = document.getElementById('myChart');
    Chart.defaults.global.animation.duration = 2000; // Animation duration
    Chart.defaults.global.title.display = false; // Remove title
    Chart.defaults.global.title.text = "Chart"; // Title
    Chart.defaults.global.title.position = 'bottom'; // Title position
    Chart.defaults.global.defaultFontColor = '#999'; // Font color
    Chart.defaults.global.defaultFontSize = 12; // Font size for every label
  
    // Chart.defaults.global.tooltips.backgroundColor = '#FFF'; // Tooltips background color
    Chart.defaults.global.tooltips.borderColor = 'white'; // Tooltips border color
    Chart.defaults.global.legend.labels.padding = 40;
    Chart.defaults.scale.ticks.beginAtZero = true;
    Chart.defaults.scale.gridLines.zeroLineColor = 'rgba(255, 255, 255, 0.1)';
    Chart.defaults.scale.gridLines.color = 'rgba(255, 255, 255, 0.02)';
  
    Chart.defaults.global.legend.display = false;
  
    var myChart = new Chart(chart, {
    type: 'doughnut',
    data: {
        labels: ["Low", "Average", "High", "Potential"],
        datasets: [{
            label: 'Final Registrants',
            data: ["12", "19", "28", "35"],
            backgroundColor: [
                '#212636','#3586ff','#4c546e','#83b5ff',
            ],
            borderColor: [
                'white',
            ],
            borderWidth: 1
        },
       ],
    },
options: {
        responsive: true,
        legend: {
            display: true,
        },
        tooltips: {
            titleFontSize: 20,
            bodyFontSize: 20,
            titleSpacing: 2,
            enabled: true,
            callbacks: {
                title: function(tooltipItem, data) {
                    return data['labels'][tooltipItem[0]['index']];
                  },
                
                label: function(tooltipItem, data) {
                  return data['datasets'][0]['data'][tooltipItem['index']] + " " + "Final Registrants";
                },
            }
        }

    },

});
    //  Chart ( 2 )
  
  
    var Chart2 = document.getElementById('myChart2').getContext('2d');
    var chart = new Chart(Chart2, {
      type: 'bar',
      data: {
        labels: ["Chicago", "Dallas", "Denver", "New York", "Toronto"],
        datasets: [{
          label: "Average",
          backgroundColor: '#3586ff',
          borderColor: '#fff',
          borderWidth: 2,
          pointBorderColor: false,
          data: [25, 18, 20, 21, 18],
          fill: false,
          lineTension: .4,
        }, {
          label: "Potential",
          fill: false,
          lineTension: .4,
          startAngle: 2,
          data: [35, 26, 29 , 35, 24],
          // , '#ff6384', '#4bc0c0', '#ffcd56', '#457ba1'
          backgroundColor: "#83b5ff",
          pointBorderColor: "#fff",
          borderColor: '#4bc0c0',
          borderWidth: 2,
          showLine: true,
        }]
      },
  
      // Configuration options
      options: {
        responsive: true,
        legend: {
            display: true,
        },
        title: {
          display: false
        },
        tooltips: {
            titleFontSize: 20,
            bodyFontSize: 20,
            titleSpacing: 2,
            enabled: true,
            
        }
      }
    });
  
    console.log(Chart.defaults.global);
  
  });